services:
  backend:
    build:
      context: .
    container_name: focinhando-backend
    ports:
      - "4444:4444"
    env_file:
      - ./.env
    volumes:
      - ./prisma:/usr/src/app/prisma
      - ./public:/usr/src/app/public
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
